### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by hdost** [perf4j/perf4j#18]

**Comment by javabrett** [comment]
I was asked the same question over email, and my answer included:

Way back in 2011 some similar questions were asked about whether a new maintainer was being sought, future etc.  Since that time I still use perf4j from time-to-time, but haven't found the need for too many more changes.  I think I have one piece of test-code change outstanding that I haven't finished or created a pull-request for.  I would say that the project is certainly in maintenance-mode.

The 2011 status thread can be viewed here: http://markmail.org/message/vgt5gulj75ux4euc .

I noticed that since CodeHaus closed-down and projects were migrated to GitHub, https://github.com/codehaus/perf4j has appeared as another import of the old, out-of-date SVN repo.  Someone should probably leave a message on that project that it is in-fact out-of-date in favour of the above repo.  It is actually code-equal to the equivalent commit in the active-repo, but was imported separately from SVN, and so shares no common commits.

**Comment by marcelstoer** [comment]
Thanks Brett for the feedback here and by email, much appreciated. 

I'm concerned about the current state of affairs here because a corporate framework dozens of projects depend upon relies on perf4j for performance logging. We see it as a risk and started looking for alternatives even though we very much like perf4j.

>  I would say that the project is certainly in maintenance-mode.

I disagree. For me a project that:
- you need to help of the Wayback Machine for just to find a public online documentation
- has pending PRs back to 2011
- has no README on GitHub
- has not released a new version for 5 years
- does not provide feedback if users raise issues
- has a public site (http://perf4j.org/) which times out when accessed

is not in "maintenance-mode" but appears to have been abandoned to die the slow bit-rot death.

> The 2011 status thread can be viewed here: http://markmail.org/message/vgt5gulj75ux4euc .

I remember that as I engaged in that discussion as well. I also offered to help back then.

> I noticed that since CodeHaus closed-down and projects were migrated to GitHub

Indeed...and CodeHaus offers https://github.com/codehaus/redirector to make sure users still find your project if they navigate to the old CodeHaus URLs. If you care I suggest you prepare a PR for all relevant files in https://github.com/codehaus/redirector/tree/master/includes.

**Comment by agrz** [comment]
I would agree that everything indicates the project looks abandoned. 
I used perf4j for the last years in several companies and would be interested to keep it alive.
As already mentioned there are several PRs hanging around for years, so it seems futile to open new ones (I would for example like to add OSGi support). 
The question I have is, if there is a chance to revive this project or would it make sense to start maintaining a fork, especially if there are others interested in the project?
I would also offer my help for any of these options.

Regards
Alexander

**Comment by javabrett** [comment]
Thanks for the notes.

In case it is not clear, I should point-out that I don't currently have push-access to perf4j/perf4j, nor have I ever had.  The only individuals I am aware of with write access are Alex (I think using "perf4j") and Xu Huisheng.  I just happened to benefit greatly from the existence of perf4j, was able to make a couple of fixes/enhancements as I went, and fortunately those changes were pulled.  In the status thread I also offered to take-up some additional role including having write-access, which was accepted, but for whatever reason did not eventuate.

>> I would say that the project is certainly in maintenance-mode.

> I disagree.

I should probably have said that differently. What I meant was that I was not personally aware of any major functionality changes that had been proposed or planned or were being worked-on, and that I would expect bug-fixes as they occur to dominate.  That doesn't mean there aren't those with plans to do new development work, I just haven't seen them.  Obviously any of that would be hampered by the lack of an agreed home-location for the project and a handful of maintainers or at least someone active with write-access.

> you need to help of the Wayback Machine for just to find a public online documentation

Sort of, if you don't want to run `mvn site` yourself, or you need it hosted.  The APT source is also available in raw-form at https://github.com/perf4j/perf4j/tree/master/src/site/apt .

> has pending PRs back to 2011

True, and there are some more recent ones now.  Are there any in particular that are high-value and that you are waiting-on?

> has no README on GitHub

I created https://github.com/perf4j/perf4j/pull/20 , a basic `README.md` created from `index.apt`.  Removed some internal links that can be put-back later.  Will be looking for a committer to pull this in.

> has a public site (http://perf4j.org/) which times out when accessed

I was trying to remember whether this was ever the public site.  I don't think it was.  DNS looks like someone is just camped on the domain - may or may not be someone previously associated with the project.

> If you care I suggest you prepare a PR for all relevant files in https://github.com/codehaus/redirector/tree/master/includes.

Certainly worth a look, especially if the project gets some pages published e.g. to GitHub pages.

My suggestion is for anyone wanting to help keep this alive or move this forward is to:

* Create a fork if you don't yet have one.
* Submit any bug fixes or enhancements.
* Create pull requests.

Then we wait and see if access to the project opens-up again from existing owners.  If not and you want to continue, either name your own fork as the new "home", or setup a new shared one.  I could probably run a release from my fork if needed.  We may have trouble getting it loaded into Maven Central etc.

**Comment by marcelstoer** [comment]
Thanks again Brett, sounds all very reasonable. I hope my comments didn't imply I'd be holding you accountable for the current state of affairs - I don't. What I didn't know though is that you don't have push-access, good you mentioned it.

@perf4j, @xuhuisheng if you don't plan to pick-up work on this dormant project could you please "elect" community members like Brett to be the new maintainers and elevate the permissions on GitHub accordingly?

**Comment by javabrett** [comment]
I noticed that the fork with perhaps the most development and commits belongs to @sovaa , who has a fork renamed to "jperf".  Might want to check out what is happening over there, get in-touch, see if they are looking for contributors, especially if succession does not occur here.

I misspoke on the domain name, and it is registered to one of the original developers, but is obviously not hosted anywhere for now.

**Comment by marcelstoer** [comment]
Interesting...the fork doesn't seem to have diverted from `master` a lot, though. It could still be merged back easily: https://github.com/perf4j/perf4j/compare/master...sovaa:master

**Comment by hdost** [comment]
Yea honestly after looking at jperf we may be better off migrating to that.
I don't mean for there to be more abandoned code on the internet, but maybe
we could have a readme which just points the new project. Or if not just
have this issue which points to it.

________________________________________

*Harold Dost* | @hdost

**Comment by sovaa** [comment]
Hi guys, I'm the one who made the jperf fork. At the company I worked for before I needed some new features implemented as well as the changes made to master since the latest release. On top of that pull-requests haven't been merged for a long time in the original project, so I forked it and implemented the features we wanted and I also merged some old pull-requests from other users and pushed a new version to maven central. Unless perf4j wants to start maintaining the original repo again pull-requests can be sent to jperf and new minor versions can be pushed to maven central. 

If someone is interested in improving/maintaining it on a regular basis I can definitely add them as a collaborator, otherwise feel free to send pull-requests and I'll merge them.

**Comment by agrz** [comment]
I think jperf is a good alternative and I will start moving to it and provide some fixes and additions I made on a private fork so far.

**Comment by ThinkpadNC5** [comment]
Hi guys，I wrote a MyPerf4J project[https://github.com/ThinkpadNC5/MyPerf4J](url), it can provide RPS, TP90, TP99 and other performance indicators.

**Comment by ThinkpadNC5** [comment]
Hi guys，I wrote a  [MyPerf4J](https://github.com/ThinkpadNC5/MyPerf4J) project, it can provide RPS, TP90, TP99 and other performance indicators.

**Comment by javabrett** [comment]
@xuhuisheng @perf4j does anyone have access to add new members?

**Comment by javabrett** [comment]
@xuhuisheng do you have perf4j org or repo admin to add new maintainers, or know who can?

**Comment by ravn** [comment]
It really sounds like this is abandoned.   I would suggest forking the project here on github and give it a new but very similar name. perf4j-nextgen for instance, and then ask Github very nicely to add a "Apparently abandoned. Please go to ...." header to the README.md file.e
